FROM public.ecr.aws/docker/library/python

RUN pip install -U pip
RUN pip install pipenv

WORKDIR /app

COPY [ "Pipfile", "Pipfile.lock", "./" ]

RUN pipenv install --system --deploy

COPY [ "predict.py", "hello.py", "model.bin", "./" ]

ENTRYPOINT [ "python", "predict.py" ]